/**
 *	IUPAC Periodic Table of Elements ver. 21.01.2011
 *	van der Waals radii from: The Cambridge Crystallographic Data Centre http://www.ccdc.cam.ac.uk/products/csd/radii/table.php4
 */
package hbondsgen.periodicTableOfElements;

import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

public class IUPACPeriodicTableOfElements {
	
	/*
	 *	Properties
	 */
	//Elements holder
	protected Map<String, IUPACElement> holder = new TreeMap<String, IUPACElement>();	
	//Singleton instance
	protected final static IUPACPeriodicTableOfElements instance = new IUPACPeriodicTableOfElements();
	
	/*
	 *	In-class constants
	 */
	//Element symbols
	public final static String H = "H";
	public final static String He = "He";
	public final static String Li = "Li";
	public final static String Be = "Be";
	public final static String B = "B";
	public final static String C = "C";
	public final static String N = "N";
	public final static String O = "O";
	public final static String F = "F";
	public final static String Ne = "Ne";
	public final static String Na = "Na";
	public final static String Mg = "Mg";
	public final static String Al = "Al";
	public final static String Si = "Si";
	public final static String P = "P";
	public final static String S = "S";
	public final static String Cl = "Cl";
	public final static String Ar = "Ar";
	public final static String K = "K";
	public final static String Ca = "Ca";
	public final static String Sc = "Sc";
	public final static String Ti = "Ti";
	public final static String V = "V";
	public final static String Cr = "Cr";
	public final static String Mn = "Mn";
	public final static String Fe = "Fe";
	public final static String Co = "Co";
	public final static String Ni = "Ni";
	public final static String Cu = "Cu";
	public final static String Zn = "Zn";
	public final static String Ga = "Ga";
	public final static String Ge = "Ge";
	public final static String As = "As";
	public final static String Se = "Se";
	public final static String Br = "Br";
	public final static String Kr = "Kr";
	public final static String Rb = "Rb";
	public final static String Sr = "Sr";
	public final static String Y = "Y";
	public final static String Zr = "Zr";
	public final static String Nb = "Nb";
	public final static String Mo = "Mo";
	public final static String Tc = "Tc";
	public final static String Ru = "Ru";
	public final static String Rh = "Rh";
	public final static String Pd = "Pd";
	public final static String Ag = "Ag";
	public final static String Cd = "Cd";
	public final static String In = "In";
	public final static String Sn = "Sn";
	public final static String Sb = "Sb";
	public final static String Te = "Te";
	public final static String I = "I";
	public final static String Xe = "Xe";
	public final static String Cs = "Cs";
	public final static String Ba = "Ba";
	public final static String La = "La";
	public final static String Ce = "Ce";
	public final static String Pr = "Pr";
	public final static String Nd = "Nd";
	public final static String Pm = "Pm";
	public final static String Sm = "Sm";
	public final static String Eu = "Eu";
	public final static String Gd = "Gd";
	public final static String Tb = "Tb";
	public final static String Dy = "Dy";
	public final static String Ho = "Ho";
	public final static String Er = "Er";
	public final static String Tm = "Tm";
	public final static String Yb = "Yb";
	public final static String Lu = "Lu";
	public final static String Hf = "Hf";
	public final static String Ta = "Ta";
	public final static String W = "W";
	public final static String Re = "Re";
	public final static String Os = "Os";
	public final static String Ir = "Ir";
	public final static String Pt = "Pt";
	public final static String Au = "Au";
	public final static String Hg = "Hg";
	public final static String Tl = "Tl";
	public final static String Pb = "Pb";
	public final static String Bi = "Bi";
	public final static String Po = "Po";
	public final static String At = "At";
	public final static String Rn = "Rn";
	public final static String Fr = "Fr";
	public final static String Ra = "Ra";
	public final static String Ac = "Ac";
	public final static String Th = "Th";
	public final static String Pa = "Pa";
	public final static String U = "U";
	public final static String Np = "Np";
	public final static String Pu = "Pu";
	public final static String Am = "Am";
	public final static String Cm = "Cm";
	public final static String Bk = "Bk";
	public final static String Cf = "Cf";
	public final static String Es = "Es";
	public final static String Fm = "Fm";
	public final static String Md = "Md";
	public final static String No = "No";
	public final static String Lr = "Lr";
	public final static String Rf = "Rf";
	public final static String Db = "Db";
	public final static String Sg = "Sg";
	public final static String Bh = "Bh";
	public final static String Hs = "Hs";
	public final static String Mt = "Mt";
	public final static String Ds = "Ds";
	public final static String Rg = "Rg";
	public final static String Cn = "Cn";
	//Element names
	protected final static String nameH = "hydrogen";
	protected final static String nameHe = "helium";
	protected final static String nameLi = "lithium";
	protected final static String nameBe = "berylium";
	protected final static String nameB = "boron";
	protected final static String nameC = "carbon";
	protected final static String nameN = "nitrogen";
	protected final static String nameO = "oxygen";
	protected final static String nameF = "fluorine";
	protected final static String nameNe = "neon";
	protected final static String nameNa = "sodium";
	protected final static String nameMg = "magnesium";
	protected final static String nameAl = "aluminium";
	protected final static String nameSi = "silicon";
	protected final static String nameP = "phosphorus";
	protected final static String nameS = "sulfur";
	protected final static String nameCl = "chlorine";
	protected final static String nameAr = "argon";
	protected final static String nameK = "potassium";
	protected final static String nameCa = "calcium";
	protected final static String nameSc = "scandium";
	protected final static String nameTi = "titanium";
	protected final static String nameV = "vanadium";
	protected final static String nameCr = "chromium";
	protected final static String nameMn = "manganese";
	protected final static String nameFe = "iron";
	protected final static String nameCo = "cobalt";
	protected final static String nameNi = "nickel";
	protected final static String nameCu = "copper";
	protected final static String nameZn = "zinc";
	protected final static String nameGa = "gallium";
	protected final static String nameGe = "germanium";
	protected final static String nameAs = "arsenic";
	protected final static String nameSe = "selenium";
	protected final static String nameBr = "bromine";
	protected final static String nameKr = "krypton";
	protected final static String nameRb = "rubidium";
	protected final static String nameSr = "strontium";
	protected final static String nameY = "yttrium";
	protected final static String nameZr = "zirconium";
	protected final static String nameNb = "niobium";
	protected final static String nameMo = "molybdenum";
	protected final static String nameTc = "technetium";
	protected final static String nameRu = "rutLinium";
	protected final static String nameRh = "rhodium";
	protected final static String namePd = "palladium";
	protected final static String nameAg = "silver";
	protected final static String nameCd = "cadmium";
	protected final static String nameIn = "indium";
	protected final static String nameSn = "tin";
	protected final static String nameSb = "antimony";
	protected final static String nameTe = "tellurium";
	protected final static String nameI = "iodine";
	protected final static String nameXe = "xenon";
	protected final static String nameCs = "caesium";
	protected final static String nameBa = "barium";
	protected final static String nameLa = "lanthanum";
	protected final static String nameCe = "cerium";
	protected final static String namePr = "praseodymium";
	protected final static String nameNd = "neodymium";
	protected final static String namePm = "promethium";
	protected final static String nameSm = "samarium";
	protected final static String nameEu = "europium";
	protected final static String nameGd = "gadolinium";
	protected final static String nameTb = "terbium";
	protected final static String nameDy = "dysprosium";
	protected final static String nameHo = "holmium";
	protected final static String nameEr = "erbium";
	protected final static String nameTm = "thulium";
	protected final static String nameYb = "ytterbium";
	protected final static String nameLu = "lutetium";
	protected final static String nameHf = "hafnium";
	protected final static String nameTa = "tantalum";
	protected final static String nameW = "tungsten";
	protected final static String nameRe = "rLinium";
	protected final static String nameOs = "osmium";
	protected final static String nameIr = "iridium";
	protected final static String namePt = "platinum";
	protected final static String nameAu = "gold";
	protected final static String nameHg = "mercury";
	protected final static String nameTl = "thallium";
	protected final static String namePb = "lead";
	protected final static String nameBi = "bismuth";
	protected final static String namePo = "polonium";
	protected final static String nameAt = "astatine";
	protected final static String nameRn = "radon";
	protected final static String nameFr = "francium";
	protected final static String nameRa = "radium";
	protected final static String nameAc = "actinium";
	protected final static String nameTh = "thorium";
	protected final static String namePa = "protactinium";
	protected final static String nameU = "uranium";
	protected final static String nameNp = "neptunium";
	protected final static String namePu = "plutonium";
	protected final static String nameAm = "americium";
	protected final static String nameCm = "curium";
	protected final static String nameBk = "berkelium";
	protected final static String nameCf = "californium";
	protected final static String nameEs = "einsteinium";
	protected final static String nameFm = "fermium";
	protected final static String nameMd = "mendelevium";
	protected final static String nameNo = "nobelium";
	protected final static String nameLr = "lawrencium";
	protected final static String nameRf = "rutherfordium";
	protected final static String nameDb = "dubnium";
	protected final static String nameSg = "seaborgium";
	protected final static String nameBh = "bohrium";
	protected final static String nameHs = "hassium";
	protected final static String nameMt = "meitnerium";
	protected final static String nameDs = "darmstadtium";
	protected final static String nameRg = "roentgenium";
	protected final static String nameCn = "copernicium";
	//Element atomic weights
	protected final Double weightH = new Double(1.007d);
	protected final Double weightHe = new Double(4.003d);
	protected final Double weightLi = new Double(6.938d);
	protected final Double weightBe = new Double(9.012d);
	protected final Double weightB = new Double(10.80d);
	protected final Double weightC = new Double(12.00d);
	protected final Double weightN = new Double(14.00d);
	protected final Double weightO = new Double(15.99d);
	protected final Double weightF = new Double(19.00d);
	protected final Double weightNe = new Double(20.18d);
	protected final Double weightNa = new Double(22.99d);
	protected final Double weightMg = new Double(24.361d);
	protected final Double weightAl = new Double(26.98d);
	protected final Double weightSi = new Double(28.08d);
	protected final Double weightP = new Double(30.97d);
	protected final Double weightS = new Double(32.05d);
	protected final Double weightCl = new Double(35.44d);
	protected final Double weightAr = new Double(39.95d);
	protected final Double weightK = new Double(39.10d);
	protected final Double weightCa = new Double(40.08d);
	protected final Double weightSc = new Double(44.96d);
	protected final Double weightTi = new Double(47.87d);
	protected final Double weightV = new Double(50.94d);
	protected final Double weightCr = new Double(52.00d);
	protected final Double weightMn = new Double(54.94d);
	protected final Double weightFe = new Double(55.85d);
	protected final Double weightCo = new Double(58.93d);
	protected final Double weightNi = new Double(58.69d);
	protected final Double weightCu = new Double(63.55d);
	protected final Double weightZn = new Double(65.38d);
	protected final Double weightGa = new Double(69.72d);
	protected final Double weightGe = new Double(72.63d);
	protected final Double weightAs = new Double(74.92d);
	protected final Double weightSe = new Double(78.96d);
	protected final Double weightBr = new Double(79.90d);
	protected final Double weightKr = new Double(83.80d);
	protected final Double weightRb = new Double(85.47d);
	protected final Double weightSr = new Double(87.62d);
	protected final Double weightY = new Double(88.91d);
	protected final Double weightZr = new Double(91.22d);
	protected final Double weightNb = new Double(92.91d);
	protected final Double weightMo = new Double(95.96d);
	protected final Double weightTc = null;
	protected final Double weightRu = new Double(101.1d);
	protected final Double weightRh = new Double(102.9d);
	protected final Double weightPd = new Double(106.4d);
	protected final Double weightAg = new Double(107.9d);
	protected final Double weightCd = new Double(112.4d);
	protected final Double weightIn = new Double(114.8d);
	protected final Double weightSn = new Double(118.7d);
	protected final Double weightSb = new Double(121.8d);
	protected final Double weightTe = new Double(127.6d);
	protected final Double weightI = new Double(126.9d);
	protected final Double weightXe = new Double(131.3d);
	protected final Double weightCs = new Double(132.9d);
	protected final Double weightBa = new Double(137.3d);
	protected final Double weightLa = new Double(138.9d);
	protected final Double weightCe = new Double(140.1d);
	protected final Double weightPr = new Double(140.9d);
	protected final Double weightNd = new Double(144.2d);
	protected final Double weightPm = null;
	protected final Double weightSm = new Double(150.4d);
	protected final Double weightEu = new Double(152.0d);
	protected final Double weightGd = new Double(157.3d);
	protected final Double weightTb = new Double(158.9d);
	protected final Double weightDy = new Double(162.5d);
	protected final Double weightHo = new Double(164.9d);
	protected final Double weightEr = new Double(167.3d);
	protected final Double weightTm = new Double(168.9d);
	protected final Double weightYb = new Double(173.1d);
	protected final Double weightLu = new Double(175.0d);
	protected final Double weightHf = new Double(178.5d);
	protected final Double weightTa = new Double(180.9d);
	protected final Double weightW = new Double(183.8d);
	protected final Double weightRe = new Double(186.2d);
	protected final Double weightOs = new Double(190.2d);
	protected final Double weightIr = new Double(192.2d);
	protected final Double weightPt = new Double(195.1d);
	protected final Double weightAu = new Double(197.0d);
	protected final Double weightHg = new Double(200.6d);
	protected final Double weightTl = new Double(204.3d);
	protected final Double weightPb = new Double(207.2d);
	protected final Double weightBi = new Double(209.0d);
	protected final Double weightPo = null;
	protected final Double weightAt = null;
	protected final Double weightRn = null;
	protected final Double weightFr = null;
	protected final Double weightRa = null;
	protected final Double weightAc = null;
	protected final Double weightTh = new Double(232.0d);
	protected final Double weightPa = new Double(231.0d);
	protected final Double weightU = new Double(238.0d);
	protected final Double weightNp = null;
	protected final Double weightPu = null;
	protected final Double weightAm = null;
	protected final Double weightCm = null;
	protected final Double weightBk = null;
	protected final Double weightCf = null;
	protected final Double weightEs = null;
	protected final Double weightFm = null;
	protected final Double weightMd = null;
	protected final Double weightNo = null;
	protected final Double weightLr = null;
	protected final Double weightRf = null;
	protected final Double weightDb = null;
	protected final Double weightSg = null;
	protected final Double weightBh = null;
	protected final Double weightHs = null;
	protected final Double weightMt = null;
	protected final Double weightDs = null;
	protected final Double weightRg = null;
	protected final Double weightCn = null;
	//Element van der Waals radii
	protected final Double radiusH = new Double(1.20d);
	protected final Double radiusHe = new Double(1.40d);
	protected final Double radiusLi = new Double(1.82d);
	protected final Double radiusBe = null;
	protected final Double radiusB = null;
	protected final Double radiusC = new Double(1.70d);
	protected final Double radiusN = new Double(1.55d);
	protected final Double radiusO = new Double(1.52d);
	protected final Double radiusF = new Double(1.47d);
	protected final Double radiusNe = new Double(1.54d);
	protected final Double radiusNa = new Double(2.27d);
	protected final Double radiusMg = new Double(1.73d);
	protected final Double radiusAl = null;
	protected final Double radiusSi = new Double(2.10d);
	protected final Double radiusP = new Double(1.80d);
	protected final Double radiusS = new Double(1.80d);
	protected final Double radiusCl = new Double(1.75d);
	protected final Double radiusAr = new Double(1.88d);
	protected final Double radiusK = new Double(2.75d);
	protected final Double radiusCa = null;
	protected final Double radiusSc = null;
	protected final Double radiusTi = null;
	protected final Double radiusV = null;
	protected final Double radiusCr = null;
	protected final Double radiusMn = null;
	protected final Double radiusFe = null;
	protected final Double radiusCo = null;
	protected final Double radiusNi = new Double(1.63d);
	protected final Double radiusCu = new Double(1.40d);
	protected final Double radiusZn = new Double(1.39d);
	protected final Double radiusGa = new Double(1.87d);
	protected final Double radiusGe = null;
	protected final Double radiusAs = new Double(1.85d);
	protected final Double radiusSe = new Double(1.90d);
	protected final Double radiusBr = new Double(1.85d);
	protected final Double radiusKr = new Double(2.02d);
	protected final Double radiusRb = null;
	protected final Double radiusSr = null;
	protected final Double radiusY = null;
	protected final Double radiusZr = null;
	protected final Double radiusNb = null;
	protected final Double radiusMo = null;
	protected final Double radiusTc = null;
	protected final Double radiusRu = null;
	protected final Double radiusRh = null;
	protected final Double radiusPd = new Double(1.63d);
	protected final Double radiusAg = new Double(1.72d);
	protected final Double radiusCd = new Double(1.58d);
	protected final Double radiusIn = new Double(1.93d);
	protected final Double radiusSn = new Double(2.17d);
	protected final Double radiusSb = null;
	protected final Double radiusTe = new Double(2.06d);
	protected final Double radiusI = new Double(1.98d);
	protected final Double radiusXe = new Double(2.16d);
	protected final Double radiusCs = null;
	protected final Double radiusBa = null;
	protected final Double radiusLa = null;
	protected final Double radiusCe = null;
	protected final Double radiusPr = null;
	protected final Double radiusNd = null;
	protected final Double radiusPm = null;
	protected final Double radiusSm = null;
	protected final Double radiusEu = null;
	protected final Double radiusGd = null;
	protected final Double radiusTb = null;
	protected final Double radiusDy = null;
	protected final Double radiusHo = null;
	protected final Double radiusEr = null;
	protected final Double radiusTm = null;
	protected final Double radiusYb = null;
	protected final Double radiusLu = null;
	protected final Double radiusHf = null;
	protected final Double radiusTa = null;
	protected final Double radiusW = null;
	protected final Double radiusRe = null;
	protected final Double radiusOs = null;
	protected final Double radiusIr = null;
	protected final Double radiusPt = new Double(1.75d);
	protected final Double radiusAu = new Double(1.66d);
	protected final Double radiusHg = new Double(1.55d);
	protected final Double radiusTl = new Double(1.96d);
	protected final Double radiusPb = new Double(2.02d);
	protected final Double radiusBi = null;
	protected final Double radiusPo = null;
	protected final Double radiusAt = null;
	protected final Double radiusRn = null;
	protected final Double radiusFr = null;
	protected final Double radiusRa = null;
	protected final Double radiusAc = null;
	protected final Double radiusTh = null;
	protected final Double radiusPa = null;
	protected final Double radiusU = new Double(1.86d);
	protected final Double radiusNp = null;
	protected final Double radiusPu = null;
	protected final Double radiusAm = null;
	protected final Double radiusCm = null;
	protected final Double radiusBk = null;
	protected final Double radiusCf = null;
	protected final Double radiusEs = null;
	protected final Double radiusFm = null;
	protected final Double radiusMd = null;
	protected final Double radiusNo = null;
	protected final Double radiusLr = null;
	protected final Double radiusRf = null;
	protected final Double radiusDb = null;
	protected final Double radiusSg = null;
	protected final Double radiusBh = null;
	protected final Double radiusHs = null;
	protected final Double radiusMt = null;
	protected final Double radiusDs = null;
	protected final Double radiusRg = null;
	protected final Double radiusCn = null;
	
	/*
	 *	Interface
	 */
	//Get singleton instance
	public static IUPACPeriodicTableOfElements getInstance() {
		return instance;
	}
	//Get all known atoms
	public Set<String> getKnownAtoms() {
		return holder.keySet();
	}
	//Get atom by symbol
	public IUPACElement getAtom(String atomic_symbol) {
		return holder.get(atomic_symbol);
	}
	//Get atom by index
	public IUPACElement getAtom(Integer atomic_index) {
		//If index is out of bounds - return null
		if(atomic_index < 1 || atomic_index > holder.size())
			return null;
		Iterator<IUPACElement> iter = holder.values().iterator();
		while(iter.hasNext())
		{
			IUPACElement atom = iter.next();
			if(atomic_index == atom.number)
				return atom;
		}
		return null;
	}
	
	/*
	 *	Constructor
	 */
	//Default constructor
	protected IUPACPeriodicTableOfElements() {
		//Fill in elements
		//H
		Integer atomic_number = 1;
		IUPACElement atom = new IUPACElement(atomic_number, H, nameH, weightH, radiusH);
		holder.put(atom.symbol, atom);
		//He
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, He, nameHe, weightHe, radiusHe);
		holder.put(atom.symbol, atom);
		//Li = "Li";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Li, nameLi, weightLi, radiusLi);
		holder.put(atom.symbol, atom);
		//Be = "Be";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Be, nameBe, weightBe, radiusBe);
		holder.put(atom.symbol, atom);
		//B = "B";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, B, nameB, weightB, radiusB);
		holder.put(atom.symbol, atom);
		//C = "C";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, C, nameC, weightC, radiusC);
		holder.put(atom.symbol, atom);
		//N = "N";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, N, nameN, weightN, radiusN);
		holder.put(atom.symbol, atom);
		//O = "O";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, O, nameO, weightO, radiusO);
		holder.put(atom.symbol, atom);
		//F = "F";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, F, nameF, weightF, radiusF);
		holder.put(atom.symbol, atom);
		//Ne = "Ne";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ne, nameNe, weightNe, radiusNe);
		holder.put(atom.symbol, atom);
		//Na = "Na";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Na, nameNa, weightNa, radiusNa);
		holder.put(atom.symbol, atom);
		//Mg = "Mg";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Mg, nameMg, weightMg, radiusMg);
		holder.put(atom.symbol, atom);
		//Al = "Al";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Al, nameAl, weightAl, radiusAl);
		holder.put(atom.symbol, atom);
		//Si = "Si";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Si, nameSi, weightSi, radiusSi);
		holder.put(atom.symbol, atom);
		//P = "P";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, P, nameP, weightP, radiusP);
		holder.put(atom.symbol, atom);
		//S = "S";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, S, nameS, weightS, radiusS);
		holder.put(atom.symbol, atom);
		//Cl = "Cl";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Cl, nameCl, weightCl, radiusCl);
		holder.put(atom.symbol, atom);
		//Ar = "Ar";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ar, nameAr, weightAr, radiusAr);
		holder.put(atom.symbol, atom);
		//K = "K";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, K, nameK, weightK, radiusK);
		holder.put(atom.symbol, atom);
		//Ca = "Ca";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ca, nameCa, weightCa, radiusCa);
		holder.put(atom.symbol, atom);
		//Sc = "Sc";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Sc, nameSc, weightSc, radiusSc);
		holder.put(atom.symbol, atom);
		//Ti = "Ti";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ti, nameTi, weightTi, radiusTi);
		holder.put(atom.symbol, atom);
		//V = "V";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, V, nameV, weightV, radiusV);
		holder.put(atom.symbol, atom);
		//Cr = "Cr";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Cr, nameCr, weightCr, radiusCr);
		holder.put(atom.symbol, atom);
		//Mn = "Mn";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Mn, nameMn, weightMn, radiusMn);
		holder.put(atom.symbol, atom);
		//Fe = "Fe";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Fe, nameFe, weightFe, radiusFe);
		holder.put(atom.symbol, atom);
		//Co = "Co";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Co, nameCo, weightCo, radiusCo);
		holder.put(atom.symbol, atom);
		//Ni = "Ni";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ni, nameNi, weightNi, radiusNi);
		holder.put(atom.symbol, atom);
		//Cu = "Cu";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Cu, nameCu, weightCu, radiusCu);
		holder.put(atom.symbol, atom);
		//Zn = "Zn";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Zn, nameZn, weightZn, radiusZn);
		holder.put(atom.symbol, atom);
		//Ga = "Ga";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ga, nameGa, weightGa, radiusGa);
		holder.put(atom.symbol, atom);
		//Ge = "Ge";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ge, nameGe, weightGe, radiusGe);
		holder.put(atom.symbol, atom);
		//As = "As";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, As, nameAs, weightAs, radiusAs);
		holder.put(atom.symbol, atom);
		//Se = "Se";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Se, nameSe, weightSe, radiusSe);
		holder.put(atom.symbol, atom);
		//Br = "Br";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Br, nameBr, weightBr, radiusBr);
		holder.put(atom.symbol, atom);
		//Kr = "Kr";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Kr, nameKr, weightKr, radiusKr);
		holder.put(atom.symbol, atom);
		//Rb = "Rb";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Rb, nameRb, weightRb, radiusRb);
		holder.put(atom.symbol, atom);
		//Sr = "Sr";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Sr, nameSr, weightSr, radiusSr);
		holder.put(atom.symbol, atom);
		//Y = "Y";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Y, nameY, weightY, radiusY);
		holder.put(atom.symbol, atom);
		//Zr = "Zr";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Zr, nameZr, weightZr, radiusZr);
		holder.put(atom.symbol, atom);
		//Nb = "Nb";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Nb, nameNb, weightNb, radiusNb);
		holder.put(atom.symbol, atom);
		//Mo = "Mo";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Mo, nameMo, weightMo, radiusMo);
		holder.put(atom.symbol, atom);
		//Tc = "Tc";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Tc, nameTc, weightTc, radiusTc);
		holder.put(atom.symbol, atom);
		//Ru = "Ru";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ru, nameRu, weightRu, radiusRu);
		holder.put(atom.symbol, atom);
		//Rh = "Rh";B
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Rh, nameRh, weightRh, radiusRh);
		holder.put(atom.symbol, atom);
		//Pd = "Pd";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Pd, namePd, weightPd, radiusPd);
		holder.put(atom.symbol, atom);
		//Ag = "Ag";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ag, nameAg, weightAg, radiusAg);
		holder.put(atom.symbol, atom);
		//Cd = "Cd";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Cd, nameCd, weightCd, radiusCd);
		holder.put(atom.symbol, atom);
		//In = "In";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, In, nameIn, weightIn, radiusIn);
		holder.put(atom.symbol, atom);
		//Sn = "Sn";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Sn, nameSn, weightSn, radiusSn);
		holder.put(atom.symbol, atom);
		//Sb = "Sb";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Sb, nameSb, weightSb, radiusSb);
		holder.put(atom.symbol, atom);
		//Te = "Te";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Te, nameTe, weightTe, radiusTe);
		holder.put(atom.symbol, atom);
		//I = "I";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, I, nameI, weightI, radiusI);
		holder.put(atom.symbol, atom);
		//Xe = "Xe";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Xe, nameXe, weightXe, radiusXe);
		holder.put(atom.symbol, atom);
		//Cs = "Cs";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Cs, nameCs, weightCs, radiusCs);
		holder.put(atom.symbol, atom);
		//Ba = "Ba";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ba, nameBa, weightBa, radiusBa);
		holder.put(atom.symbol, atom);
		//La = "La";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, La, nameLa, weightLa, radiusLa);
		holder.put(atom.symbol, atom);
		//Ce = "Ce";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ce, nameCe, weightCe, radiusCe);
		holder.put(atom.symbol, atom);
		//Pr = "Pr";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Pr, namePr, weightPr, radiusPr);
		holder.put(atom.symbol, atom);
		//Nd = "Nd";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Nd, nameNd, weightNd, radiusNd);
		holder.put(atom.symbol, atom);
		//Pm = "Pm";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Pm, namePm, weightPm, radiusPm);
		holder.put(atom.symbol, atom);
		//Sm = "Sm";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Sm, nameSm, weightSm, radiusSm);
		holder.put(atom.symbol, atom);
		//Eu = "Eu";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Eu, nameEu, weightEu, radiusEu);
		holder.put(atom.symbol, atom);
		//Gd = "Gd";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Gd, nameGd, weightGd, radiusGd);
		holder.put(atom.symbol, atom);
		//Tb = "Tb";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Tb, nameTb, weightTb, radiusTb);
		holder.put(atom.symbol, atom);
		//Dy = "Dy";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Dy, nameDy, weightDy, radiusDy);
		holder.put(atom.symbol, atom);
		//Ho = "Ho";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ho, nameHo, weightHo, radiusHo);
		holder.put(atom.symbol, atom);
		//Er = "Er";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Er, nameEr, weightEr, radiusEr);
		holder.put(atom.symbol, atom);
		//Tm = "Tm";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Tm, nameTm, weightTm, radiusTm);
		holder.put(atom.symbol, atom);
		//Yb = "Yb";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Yb, nameYb, weightYb, radiusYb);
		holder.put(atom.symbol, atom);
		//Lu = "Lu";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Lu, nameLu, weightLu, radiusLu);
		holder.put(atom.symbol, atom);
		//Hf = "Hf";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Hf, nameHf, weightHf, radiusHf);
		holder.put(atom.symbol, atom);
		//Ta = "Ta";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ta, nameTa, weightTa, radiusTa);
		holder.put(atom.symbol, atom);
		//W = "W";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, W, nameW, weightW, radiusW);
		holder.put(atom.symbol, atom);
		//Re = "Re";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Re, nameRe, weightRe, radiusRe);
		holder.put(atom.symbol, atom);
		//Os = "Os";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Os, nameOs, weightOs, radiusOs);
		holder.put(atom.symbol, atom);
		//Ir = "Ir";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ir, nameIr, weightIr, radiusIr);
		holder.put(atom.symbol, atom);
		//Pt = "Pt";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Pt, namePt, weightPt, radiusPt);
		holder.put(atom.symbol, atom);
		//Au = "Au";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Au, nameAu, weightAu, radiusAu);
		holder.put(atom.symbol, atom);
		//Hg = "Hg";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Hg, nameHg, weightHg, radiusHg);
		holder.put(atom.symbol, atom);
		//Tl = "Tl";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Tl, nameTl, weightTl, radiusTl);
		holder.put(atom.symbol, atom);
		//Pb = "Pb";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Pb, namePb, weightPb, radiusPb);
		holder.put(atom.symbol, atom);
		//Bi = "Bi";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Bi, nameBi, weightBi, radiusBi);
		holder.put(atom.symbol, atom);
		//Po = "Po";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Po, namePo, weightPo, radiusPo);
		holder.put(atom.symbol, atom);
		//At = "At";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, At, nameAt, weightAt, radiusAt);
		holder.put(atom.symbol, atom);
		//Rn = "Rn";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Rn, nameRn, weightRn, radiusRn);
		holder.put(atom.symbol, atom);
		//Fr = "Fr";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Fr, nameFr, weightFr, radiusFr);
		holder.put(atom.symbol, atom);
		//Ra = "Ra";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ra, nameRa, weightRa, radiusRa);
		holder.put(atom.symbol, atom);
		//Ac = "Ac";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ac, nameAc, weightAc, radiusAc);
		holder.put(atom.symbol, atom);
		//Th = "Th";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Th, nameTh, weightTh, radiusTh);
		holder.put(atom.symbol, atom);
		//Pa = "Pa";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Pa, namePa, weightPa, radiusPa);
		holder.put(atom.symbol, atom);
		//U = "U";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, U, nameU, weightU, radiusU);
		holder.put(atom.symbol, atom);
		//Np = "Np";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Np, nameNp, weightNp, radiusNp);
		holder.put(atom.symbol, atom);
		//Pu = "Pu";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Pu, namePu, weightPu, radiusPu);
		holder.put(atom.symbol, atom);
		//Am = "Am";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Am, nameAm, weightAm, radiusAm);
		holder.put(atom.symbol, atom);
		//Cm = "Cm";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Cm, nameCm, weightCm, radiusCm);
		holder.put(atom.symbol, atom);
		//Bk = "Bk";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Bk, nameBk, weightBk, radiusBk);
		holder.put(atom.symbol, atom);
		//Cf = "Cf";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Cf, nameCf, weightCf, radiusCf);
		holder.put(atom.symbol, atom);
		//Es = "Es";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Es, nameEs, weightEs, radiusEs);
		holder.put(atom.symbol, atom);
		//Fm = "Fm";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Fm, nameFm, weightFm, radiusFm);
		holder.put(atom.symbol, atom);
		//Md = "Md";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Md, nameMd, weightMd, radiusMd);
		holder.put(atom.symbol, atom);
		//No = "No";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, No, nameNo, weightNo, radiusNo);
		holder.put(atom.symbol, atom);
		//Lr = "Lr";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Lr, nameLr, weightLr, radiusLr);
		holder.put(atom.symbol, atom);
		//Rf = "Rf";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Rf, nameRf, weightRf, radiusRf);
		holder.put(atom.symbol, atom);
		//Db = "Db";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Db, nameDb, weightDb, radiusDb);
		holder.put(atom.symbol, atom);
		//Sg = "Sg";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Sg, nameSg, weightSg, radiusSg);
		holder.put(atom.symbol, atom);
		//Bh = "Bh";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Bh, nameBh, weightBh, radiusBh);
		holder.put(atom.symbol, atom);
		//Hs = "Hs";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Hs, nameHs, weightHs, radiusHs);
		holder.put(atom.symbol, atom);
		//Mt = "Mt";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Mt, nameMt, weightMt, radiusMt);
		holder.put(atom.symbol, atom);
		//Ds = "Ds";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Ds, nameDs, weightDs, radiusDs);
		holder.put(atom.symbol, atom);
		//Rg = "Rg";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Rg, nameRg, weightRg, radiusRg);
		holder.put(atom.symbol, atom);
		//Cn = "Cn";
		atomic_number = atomic_number + 1;
		atom = new IUPACElement(atomic_number, Cn, nameCn, weightCn, radiusCn);
		holder.put(atom.symbol, atom);
	}
}
